# Array 2 dan 3 dimensi

In [14]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [15]:
arr2 = np.array([[[1,2],[1,2]], [[1,2],[1,2]], [[1,2],[1,2]]])

In [16]:
arr2

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2]]])

In [17]:
arr2.ndim

3

In [18]:
# Buatlah array 4-5 dimensi