# Indexing

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [2]:
len(arr)

5

In [3]:
for i in range (len(arr)):
    print(f" indeks ke {i} -> {arr[i]}")

 indeks ke 0 -> 1
 indeks ke 1 -> 2
 indeks ke 2 -> 3
 indeks ke 3 -> 4
 indeks ke 4 -> 5


# Negative Indexing

In [8]:
i = -1
while (i != -(len(arr))-1) :
    print(f"Indeks ke {i} -> {arr[i]}")
    i-=1

Indeks ke -1 -> 5
Indeks ke -2 -> 4
Indeks ke -3 -> 3
Indeks ke -4 -> 2
Indeks ke -5 -> 1


# Slicing 

In [9]:
# Slcing pada array numpy sama dengan list 

arr[:]

array([1, 2, 3, 4, 5])

In [10]:
arr[2:4]

array([3, 4])

In [13]:
arr[1:3]

array([2, 3])

# Slicing with Step

In [14]:
arr[::-1]

array([5, 4, 3, 2, 1])

In [15]:
arr[-2::-1]

array([4, 3, 2, 1])

# Slicing using list as positions

In [16]:
arr

array([1, 2, 3, 4, 5])

In [21]:
li = [1,4]

In [22]:
arr[li] # Mencari array dengan indeks 1 dan 4

array([2, 5])

In [19]:
li = [1,4,-1]
arr[li]

array([2, 5, 5])